### ISSUE TITLE
I'm getting a lot of errors

### ISSUE THREAD

**Issue by agustdaegu** [nathan-149/automated_youtube_channel#10]
hello, I'm getting these errors. can somebody help me? thanks in advance.

`Scraping Videos...
Starting Scraping 

[...]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Name\Desktop\Python\automated_youtube_channel\main.py", line 145, in <module>
    attemptRoutine()
  File "C:\Users\Name\Desktop\Python\automated_youtube_channel\main.py", line 136, in attemptRoutine
    routine()
  File "C:\Users\Name\Desktop\Python\automated_youtube_channel\main.py", line 90, in routine
    scrapeVideos(username = IG_USERNAME,
  File "C:\Users\Name\Desktop\Python\automated_youtube_channel\scrape_videos.py", line 18, in scrapeVideos
    L.login(username, password)
  File "C:\Users\Name\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloader.py", line 483, in login
    self.context.login(user, passwd)
  File "C:\Users\Name\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloadercontext.py", line 226, in login
    raise ConnectionException("Login error: JSON decode fail, {} - {}.".format(login.status_code, login.reason))
instaloader.exceptions.ConnectionException: Login error: JSON decode fail, 403 - Forbidden.`

**Comment by damibal** [comment]
Hello...me too...if you find the solution, please let me know

Best regards

**Comment by vinswat** [comment]
Hi there, 
me three, been trying all day but no luck. think its related to instaloader.

**Comment by WeTheArtist** [comment]
Same here. Anyone found a solution?

**Comment by gree303** [comment]
Any news on this?

**Comment by DevTheDruid** [comment]
Anyone ever figure it out?

**Comment by cooperskickz** [comment]
any solutions?

**Comment by TheAustrian420** [comment]
any solutions?
