### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) ERROR

### ISSUE THREAD

**Issue by damibal** [nathan-149/automated_youtube_channel#11]
Hello community,

I need help to fix this error.
I thank you in advance

Starting Scraping
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 224, in login
    resp_json = login.json()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Best regards

**Comment by 40hunnid** [comment]
hey maaayn.

the error is related to instaloader as I'm sure you already know. Its potentially due to a change from a third parties platform that instaloader uses to function. Therefore we could be potentially trying to fix a bug that isn't fixable. 

within the program instaloader is responsible for certain things, but instaloader as a library can be replaced with a different library alongside all its functions. 

for example theres:
instascrape       pip install insta-scrape
instascraper      pip install instascraper

heres a link to others that could potentially work: https://awesomeopensource.com/projects/instagram-scraper

Again, if everyone that's getting this recent issue can put in some research we will find a solution pretty quick. 

Thanks

**Comment by damibal** [comment]
Hello 40hunnid...thank you very much for your suggestions...I will try   It...

Best regards and many thanks
