### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by AidanTheBandit1** [nathan-149/automated_youtube_channel#16]
I keep getting this error 
Total Length: 0
Traceback (most recent call last):
  File "c:\Users\betha\Downloads\automated_youtube_channel-master\automated_youtube_channel-master\main.py", line 146, in <module>
    attemptRoutine()
  File "c:\Users\betha\Downloads\automated_youtube_channel-master\automated_youtube_channel-master\main.py", line 137, in attemptRoutine
    routine()
  File "c:\Users\betha\Downloads\automated_youtube_channel-master\automated_youtube_channel-master\main.py", line 102, in routine
    makeCompilation(path = videoDirectory,
  File "c:\Users\betha\Downloads\automated_youtube_channel-master\automated_youtube_channel-master\make_compilation.py", line 94, in makeCompilation
    finalClip = concatenate_videoclips(videos, method="compose")
  File "C:\Users\betha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\moviepy\video\compositing\concatenate.py", line 75, in concatenate_videoclips
    w = max(r[0] for r in sizes)
ValueError: max() arg is an empty sequence
PS C:\Users\betha\Downloads\automated_youtube_channel-master>

**Comment by gd2003gamingchamp** [comment]
Facing same critical issue, found any solutions?

**Comment by AidanTheBandit1** [comment]
No:(

**Comment by nathan-149** [comment]
This means that there's no videos in the path that you pass to makeCompilation. Check that you are downloading to the right folder (so after you download the videos, if should be in a path, like "./videos"). If there are videos that are within the minimum and maximum time requirements in make_compilation.py, this should fix this issue.

**Comment by tarun0206** [comment]
Check whether the folder name is correct or not, this error comes when movie.py is not able to find any files in the given file path.

**Comment by Astolfo-USBPico** [comment]
> This means that there's no videos in the path that you pass to makeCompilation. Check that you are downloading to the right folder (so after you download the videos, if should be in a path, like "./videos"). If there are videos that are within the minimum and maximum time requirements in make_compilation.py, this should fix this issue.

I NEED YOUR HELP PLEASE NATHAN! so i get that error but also i get this error when scraping skipped "theinstauser" because of "graphql" LIKE TF IS GRAPHQL HELPPPPPP MEEEEEEEEEEEEEEEEEEEEEEEE
