### ISSUE TITLE
I'm getting a lot of errors!

### ISSUE THREAD

**Issue by arcasull2020** [nathan-149/automated_youtube_channel#19]
Traceback (most recent call last):
  File "C:\Users\arcas\Desktop\automated_youtube_channel-master\main.py", line 145, in <module>
    attemptRoutine()
  File "C:\Users\arcas\Desktop\automated_youtube_channel-master\main.py", line 136, in attemptRoutine
    routine()
  File "C:\Users\arcas\Desktop\automated_youtube_channel-master\main.py", line 71, in routine
    creds = flow.run_console()
  File "C:\Users\arcas\AppData\Local\Programs\Python\Python39\lib\site-packages\google_auth_oauthlib\flow.py", line 414, in run_console
    self.fetch_token(code=code)
  File "C:\Users\arcas\AppData\Local\Programs\Python\Python39\lib\site-packages\google_auth_oauthlib\flow.py", line 288, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
  File "C:\Users\arcas\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_oauthlib\oauth2_session.py", line 246, in fetch_token
    raise ValueError(
ValueError: Please supply either code or authorization_response parameters.

This is the error message. Could anybody help me fix it?

Best regards

**Comment by sam5epi0l** [comment]
Bro this is just 1 error only!!
did you saved the `googleAPI.json` in script directory.
