### ISSUE TITLE
After running the main.py , i got these errors 

### ISSUE THREAD

**Issue by pavlospct** [nathan-149/automated_youtube_channel#20]
Traceback (most recent call last):
  File "/Users/pavlos/Desktop/automated_youtube_channel/venv/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 202, in login
    resp_json = login.json()
  File "/Users/pavlos/Desktop/automated_youtube_channel/venv/lib/python3.9/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pavlos/Desktop/automated_youtube_channel/main.py", line 145, in <module>
    attemptRoutine()
  File "/Users/pavlos/Desktop/automated_youtube_channel/main.py", line 136, in attemptRoutine
    routine()
  File "/Users/pavlos/Desktop/automated_youtube_channel/main.py", line 90, in routine
    scrapeVideos(username = IG_USERNAME,
  File "/Users/pavlos/Desktop/automated_youtube_channel/scrape_videos.py", line 18, in scrapeVideos
    L.login(username, password)  
  File "/Users/pavlos/Desktop/automated_youtube_channel/venv/lib/python3.9/site-packages/instaloader/instaloader.py", line 425, in login
    self.context.login(user, passwd)
  File "/Users/pavlos/Desktop/automated_youtube_channel/venv/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 204, in login
    raise ConnectionException("Login error: JSON decode fail, {} - {}.".format(login.status_code, login.reason))
instaloader.exceptions.ConnectionException: Login error: JSON decode fail, 400 - Bad Request.

**Comment by ZaryImortal** [comment]
not logging in

**Comment by cooperskickz** [comment]
got the issue how do i fix this
