### ISSUE TITLE
Skipping all accounts

### ISSUE THREAD

**Issue by timmit147** [nathan-149/automated_youtube_channel#25]
# Skipping all accounts

Everyting worked I have uploaded 5 videos to my youtube channel but now it skipping all my channels?

## Code

<instaloader.nodeiterator.NodeIterator object at 0x0000023B3601DD60>
Scraping From Account: funny_videos
Skipped acc funny_videosbecause of
user not found: 'funny_videos'
Scraping From Account: funny.homevideos
Skipped acc funny.homevideosbecause of
user not found: 'funny.homevideos'
Scraping From Account: try_not_to_laugh_funny_videos
Skipped acc try_not_to_laugh_funny_videosbecause of
user not found: 'try_not_to_laugh_funny_videos'
Scraping From Account: cattoseverywhere
Skipped acc cattoseverywherebecause of
user not found: 'cattoseverywhere'
Scraping From Account: cattobrat
Skipped acc cattobratbecause of
user not found: 'cattobrat'
Scraping From Account: memerzvidz
Skipped acc memerzvidzbecause of
user not found: 'memerzvidz'
Scraping From Account: fuckjerry.tv
Skipped acc fuckjerry.tvbecause of
user not found: 'fuckjerry.tv'
Scraped Videos!
Making Compilation...
Total Length: 0
Traceback (most recent call last):
  File "C:\Users\Gebruiker\Desktop\automated_youtube_channel-master\main.py", line 144, in <module>
    attemptRoutine()
  File "C:\Users\Gebruiker\Desktop\automated_youtube_channel-master\main.py", line 135, in attemptRoutine
    routine()
  File "C:\Users\Gebruiker\Desktop\automated_youtube_channel-master\main.py", line 100, in routine
    makeCompilation(path = videoDirectory,
  File "C:\Users\Gebruiker\Desktop\automated_youtube_channel-master\make_compilation.py", line 94, in makeCompilation
    finalClip = concatenate_videoclips(videos, method="compose")
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\compositing\concatenate.py", line 75, in concatenate_videoclips
    w = max(r[0] for r in sizes)
ValueError: max() arg is an empty sequence

C:\Users\Gebruiker\Desktop\automated_youtube_channel-master>

**Comment by nessquin** [comment]
How to fix it?

**Comment by DWAA1660** [comment]
having same issue

**Comment by burakclk1** [comment]
same issue

**Comment by burakclk1** [comment]
any solution?
