### ISSUE TITLE
attempting to try it but getting syntax errors

### ISSUE THREAD

**Issue by leapwav** [nathan-149/automated_youtube_channel#28]
can't tell how i can fix this?

Traceback (most recent call last):
  File "C:\Users\leap\Dropbox\My PC (DESKTOP-7IBEVFE)\Desktop\automated_youtube_channel-master\main.py", line 1, in <module>
    from scrape_videos import scrapeVideos
  File "C:\Users\leap\Dropbox\My PC (DESKTOP-7IBEVFE)\Desktop\automated_youtube_channel-master\scrape_videos.py", line 2, in <module>
    import dateutil.relativedelta
ModuleNotFoundError: No module named 'dateutil'

**Comment by sam5epi0l** [comment]
First, You need to install requirements using this command. (btw, I recommend using Linux)
`pip3 install -r requirements.txt `

**Comment by leapwav** [comment]
cheers
