### ISSUE TITLE
How To Get The Api Key Or The .json File 

### ISSUE THREAD

**Issue by faded-ninja** [nathan-149/automated_youtube_channel#3]
When I Run The Program , I Get This Error 

```Matplotlib created a temporary config/cache directory at /tmp/matplotlib-596dvi75 because the default path (/config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 203, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'googleAPI.json'```

How About You Make A New Video How To Get The Api Key , Or Can You Just Teach me In My Dms , My Username Is ₣₳Đ3Đ ₦1₦J₳#1371 In Discord , Thank You Soo Much For The Code

**Comment by NoNam44** [comment]
You missing googleAPI.json file ! Follow the guide https://developers.google.com/youtube/v3/quickstart/python to get that file !
