### ISSUE TITLE
skipped userHERE because of graphql I ALSO HAVE ANOTHER ISSUE! PLEASE HELP!!!!

### ISSUE THREAD

**Issue by Astolfo-USBPico** [nathan-149/automated_youtube_channel#34]
2022 3 12 23 11 14
./MAR_2022_v12.mp4
Scraping Videos...
Starting Scraping
<instaloader.nodeiterator.NodeIterator object at 0x000001605261FC70>
Scraping From Account: funnyposts
Skipped acc funnypostsbecause of
'graphql'
Scraping From Account: tweets
Skipped acc tweetsbecause of
'graphql'
Scraping From Account: epicfunnypage
Downloaded 0 videos successfully

Scraping From Account: lmao
Skipped acc lmaobecause of
'graphql'
Scraping From Account: ight
Skipped acc ightbecause of
'graphql'
Scraping From Account: memezar
Skipped acc memezarbecause of
'graphql'
Scraping From Account: meme.ig
Downloaded 0 videos successfully

Scraped Videos!
Making Compilation...
Total Length: 0
Traceback (most recent call last):
  File "C:\Users\sound\OneDrive\Desktop\chrome downloads\automated_youtube_channel-master\automated_youtube_channel-master\main.py", line 145, in <module>
    attemptRoutine()
  File "C:\Users\sound\OneDrive\Desktop\chrome downloads\automated_youtube_channel-master\automated_youtube_channel-master\main.py", line 136, in attemptRoutine
    routine()
  File "C:\Users\sound\OneDrive\Desktop\chrome downloads\automated_youtube_channel-master\automated_youtube_channel-master\main.py", line 101, in routine
    makeCompilation(path = videoDirectory,
  File "C:\Users\sound\OneDrive\Desktop\chrome downloads\automated_youtube_channel-master\automated_youtube_channel-master\make_compilation.py", line 94, in makeCompilation
    finalClip = concatenate_videoclips(videos, method="compose")
  File "C:\Users\sound\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\compositing\concatenate.py", line 75, in concatenate_videoclips

so you can see both errors i get :/ I get the skipped because of 'graphql' and the downloaded 0 videos, and the smth smth smth idk just above this text

**Comment by Condence** [comment]
same problem

**Comment by gree303** [comment]
same problem, any clue?

Handling GoogleAPI
2022 5 1 22 24 16
./MAY_2022_v1.mp4
Scraping Videos...
Starting Scraping
<instaloader.nodeiterator.NodeIterator object at 0x7feb61bed3c8>
Scraping From Account: meme.collector.8
Downloaded 0 videos successfully

Scraping From Account: itz.the.nature
Skipped acc itz.the.naturebecause of
'graphql'
Scraping From Account: _relax.with.nature_
Downloaded 0 videos successfully

Scraped Videos!
Making Compilation...
Total Length: 0
Traceback (most recent call last):
  File "main.py", line 145, in <module>
    attemptRoutine()
  File "main.py", line 136, in attemptRoutine
    routine()
  File "main.py", line 107, in routine
    outputFile = outputFile)
  File "automated_youtube_channel-master/make_compilation.py", line 94, in makeCompilation
    finalClip = concatenate_videoclips(videos, method="compose")
  File "/.local/lib/python3.5/site-packages/moviepy/video/compositing/concatenate.py", line 75, in concatenate_videoclips
    w = max(r[0] for r in sizes)
ValueError: max() arg is an empty sequence

**Comment by gree303** [comment]
When I understand this correct, the following just happens because no videos had been downloaded before.

Traceback (most recent call last):
File "main.py", line 145, in
attemptRoutine()
File "main.py", line 136, in attemptRoutine
routine()
File "main.py", line 107, in routine
outputFile = outputFile)
File "automated_youtube_channel-master/make_compilation.py", line 94, in makeCompilation
finalClip = concatenate_videoclips(videos, method="compose")
File "/.local/lib/python3.5/site-packages/moviepy/video/compositing/concatenate.py", line 75, in concatenate_videoclips
w = max(r[0] for r in sizes)
ValueError: max() arg is an empty sequence

So, the issue is more with downloading 0 videos, i suspect (?)
