### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by w31rdho** [nathan-149/automated_youtube_channel#36]
Scraping Videos...
Starting Scraping
<instaloader.nodeiterator.NodeIterator object at 0x0000029E8B455F28>
Traceback (most recent call last):
  File "main.py", line 145, in <module>
    attemptRoutine()
  File "main.py", line 136, in attemptRoutine
    routine()
  File "main.py", line 93, in routine
    days=1)
  File "C:\Users\mrdho\Dropbox\automated_youtube_channel-master\scrape_videos.py", line 28, in scrapeVideos
    looter = ProfileLooter(acc, videos_only=True, template="{id}-{username}-{width}-{height}")
  File "C:\Python3\lib\site-packages\instalooter\looters.py", line 705, in __init__
    super(ProfileLooter, self).__init__(**kwargs)
  File "C:\Python3\lib\site-packages\instalooter\looters.py", line 287, in __init__
    token = get_shared_data(res.text)['config']['csrf_token']
  File "C:\Python3\lib\site-packages\instalooter\_utils.py", line 94, in get_shared_data
    return json.loads(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by w31rdho** [comment]
does anyone have the same problem?

**Comment by Animesh-Barai** [comment]
yes i have the same problem and not getting any solution in the internet  can anyone please tell me where i am making mistake??

**Comment by facudelucia** [comment]
same problem :(

**Comment by Jinkxx** [comment]
Currently stuck with the same error. Does anyone know a solution?

**Comment by metaltiger775** [comment]
No and it's starting to get annoying :(

**Comment by KalikHub** [comment]
Anyone got a solution!?
pleasee

**Comment by KarthikeyaPatnala12** [comment]
It looks like you are trying to scrape videos from Instagram using Instalooter, and you are encountering an AttributeError with the message "'NoneType' object has no attribute 'group'. This error is raised because the "get_shared_data" function in Instalooter is unable to extract the shared data from the HTML page.

There could be a few reasons for this. One possibility is that the Instagram page you are trying to scrape has changed its structure, and the get_shared_data function can no longer find the shared data. Another possibility is an issue with the HTML page you are trying to scrape, such as a syntax error or a missing element.

To troubleshoot this issue, you can try the following steps:
1. Make sure that you are using the latest version of Instalooter.
2. Check the HTML page you are trying to scrape to see if there are any obvious issues, such as syntax errors or missing elements.

3.  Try scraping a different Instagram page to see if the issue persists.

4.  Check the Instalooter documentation or the source code for the get_shared_data function to see if there are any updates or changes that may have caused the issue.

I hope these suggestions help you resolve the issue with your Instagram video scraping.

**Comment by oranmcclintock** [comment]
Instagram probably updated something in their code making instalooter break

**Comment by FoxYolk** [comment]
Help, I am stuck on the same problem
