### ISSUE TITLE
anyone know how to fix this error ?

### ISSUE THREAD

**Issue by BHTungAnh** [nathan-149/automated_youtube_channel#40]
E:\automated_youtube_channel-master>python3 main.py
Handling GoogleAPI
2022 7 2 9 40 48
./JULY_2022_v2.mp4
Scraping Videos...
Starting Scraping
<instaloader.nodeiterator.NodeIterator object at 0x00000143CFC357E0>
Traceback (most recent call last):
  File "E:\automated_youtube_channel-master\main.py", line 145, in <module>
    attemptRoutine()
  File "E:\automated_youtube_channel-master\main.py", line 136, in attemptRoutine
    routine()
  File "E:\automated_youtube_channel-master\main.py", line 90, in routine
    scrapeVideos(username = IG_USERNAME,
  File "E:\automated_youtube_channel-master\scrape_videos.py", line 28, in scrapeVideos
    looter = ProfileLooter(acc, videos_only=True, template="{id}-{username}-{width}-{height}")
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instalooter\looters.py", line 705, in __init__
    super(ProfileLooter, self).__init__(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instalooter\looters.py", line 287, in __init__
    token = get_shared_data(res.text)['config']['csrf_token']
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instalooter\_utils.py", line 94, in get_shared_data
    return json.loads(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

does anyone know how to fix this ?

**Comment by bobayagafrfr** [comment]
how fix
