### ISSUE TITLE
Login error: Token Not Found

### ISSUE THREAD

**Issue by slajuwomi** [nathan-149/automated_youtube_channel#51]
Traceback (most recent call last):
  File "C:\Users\Stephen Lajuwomi\Downloads\AutomatedCompilationChannel-master\main.py", line 15, in <module>
    scrapeVideos(username = InstagramLoginInfo.InstagramId,
  File "C:\Users\Stephen Lajuwomi\Downloads\AutomatedCompilationChannel-master\ScrapeVideos.py", line 34, in scrapeVideos
    looter.login(username, password)
  File "C:\Users\Stephen Lajuwomi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instalooter\looters.py", line 547, in login
    self._login(username, password, session=self.session)
  File "C:\Users\Stephen Lajuwomi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instalooter\looters.py", line 180, in _login
    raise SystemError('Login error: Token not found')
SystemError: Login error: Token not found

**Comment by popat25** [comment]
Hello did you find any solution?
